FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Ważne: do Postgres potrzebujesz psycopg2-binary
RUN pip install psycopg2-binary
COPY . .
CMD ["uvicorn", "app.backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
ENV LANG C.UTF-8