FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["streamlit", "run", "app/frontend/main_frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]
ENV LANG C.UTF-8